M48
; DRILL file {KiCad (6.0.4)} date Mon Jul 18 11:06:24 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-07-18T11:06:24+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0689
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0886
%
G90
G05
T1
X5.5929Y-3.5714
X7.1677Y-3.5714
T2
X5.898Y-3.4533
X6.902Y-3.4533
T0
M30
